### PR TITLE
missing tags & files

### PR DESCRIPTION
**Pull request by ArxdSilva**
Hello! This PR is a 'help' generated by a [tool](https://github.com/XML-Comp/XML-Comp) that I did to compare a translation with the English version and tell the translators what you're missing in the game! 

These are the tags that you need to add, It'll be good to add into the project and as people fix them, they remove It.

### CODE REVIEW

**Comment by Kunegard** [comment]
Which files were you comparing translation with?
We saw your tool, but Tynan's tool some of that tags shows as incorrect, unused - we were trying them a while ago.

**Comment by ArxdSilva** [comment]
I compared to the latest English version on Steam's folder

**Comment by ArxdSilva** [comment]
The same way that it's used on the repository example

**Comment by Nalthe** [comment]
You know, I checked in my files and e.g. there is no tag like <ColonyGainsName>. There WAS such tag, but it was changed in A16 - and now there are few tags that are associated with it. And the same is with other tags. Are you sure you are using the newest files? Cause it looks like these are from A15, not A16.

**Comment by ArxdSilva** [comment]
Sorry, I've totaly forgotten to update on this PC, just fixed It. Looks like there's nothing important missing. Thanks for your time!

**Comment by Nalthe** [comment]
No problem and thank you for trying to help ^^

**Pull request closed without merging**
